### ISSUE TITLE
API - filtering not working as expected

### ISSUE THREAD

**Issue by akuljana** [ridwanskaterock/cicool#122]
I have records with **ID_something** field.
When I want to filter records by specific **ID_something** (2 for example) I get result with **ID_something** 22, 12,... etc

/api/all/?filter=2&field=ID_something

How to fix this?

**Comment by ridwanskaterock** [comment]
do you mean you get more than 1 data? when filtering with ID_something ?

**Comment by ridwanskaterock** [comment]
can you add this code
after `model_{module_name}->get(`

`echo $this->db->last_query();`

for see query is correct or no 

thanks

**Comment by akuljana** [comment]
When I want **all** records with ID_somenthing = 2 I get records with ID_something = 12 and records with ID _something = 20,... (it returns all records that contains 2 which is not ok)

**Comment by ridwanskaterock** [comment]
can you try it for debbuging 
after $this->model_{module_name}->get(

echo $this->db->last_query();

? thanks

**Comment by ridwanskaterock** [comment]
and can i see your model ? 
you only able to search field in list field search 
![image](https://user-images.githubusercontent.com/9270445/32363458-10eb6cc8-c0a2-11e7-89cc-513402fed384.png)

**Comment by akuljana** [comment]
![image](https://user-images.githubusercontent.com/2221952/32363781-47cafa46-c071-11e7-8faa-df9e70047756.png)

Please check this, this is from your demo on: http://cicool.ridwans.com/administrator/rest/view/2

**Comment by ridwanskaterock** [comment]
oh okay because the search field algorithm uses like so the existing category no 2 will appear

for it you can change this code 

![image](https://user-images.githubusercontent.com/9270445/32364181-06337646-c0a6-11e7-9416-a9967e020b2c.png)

`$where .= "(" . "blog.".$field . " = '" . $q . "' )";`

and do same on this function 

![image](https://user-images.githubusercontent.com/9270445/32364226-3febd568-c0a6-11e7-80c4-d801f989bfa3.png)

**Comment by akuljana** [comment]
Thank you!
