### ISSUE TITLE
Upload File

### ISSUE THREAD

**Issue by rumytaulu** [ridwanskaterock/cicool#142]
Salam,
Apakah ada cara untuk membuat kolom upload file via crud cicool?
(upload ke server bukan ke database)

**Comment by ridwanskaterock** [comment]
Untuk upload di cicool memang tidak mengupload file ke database tapi
menyimpan pada direktory server, yg di simpan pada database hanya nama file
saja.

Untuk tutorial membuat CRUD dan lain lain silahkan lihat pada channel
YouTube saya / dokumentasi

Trimakasih

Pada tanggal 4 Jan 2018 09:39, "rumytaulu" <notifications@github.com>
menulis:

Salam,
Apakah ada cara untuk membuat kolom upload file via crud cicool?
(upload ke server bukan ke database)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ridwanskaterock/cicool/issues/142>, or mute the thread

**Comment by rumytaulu** [comment]
Terima kasih jawabannya.
