### ISSUE TITLE
Wizard keeps coming up...

### ISSUE THREAD

**Issue by thenewN** [ridwanskaterock/cicool#34]
I have successfully completed the wizard....but after the last step, where I just have to click "Finished" it does not take me to a login or so. It just starts the wizard all over again. 

Any ideas?

**Comment by ridwanskaterock** [comment]
for login and password you can use email and password that you enter on the installation wizzard, ?

thanks

**Comment by ridwanskaterock** [comment]
if wizzard has finished you can go to

example.com/administrator/login

**Comment by thenewN** [comment]
The wizzard says its finished. The database is filled and the user is also created. However, if I want to access /administrator/login it refers me to the wizzard again. If I proceed it even says that the user already exists. This is a loop.

**Comment by ridwanskaterock** [comment]
Can i see the screenshoot notification install finish ?
What you found file application/config/site.php

If you not see the file maybe this problem cause the folder application/config not writable

You can create manualy file application/config/site.php on your application thanks

**Comment by adadion** [comment]
Same thing happened to me mas Ridwan. I tried to fill the installation with the same data, at the end it says account already exist with that username. Please enter a different username, or if you forgot your password, please click the link below.
Email address already exists on the system. If you forgot your password, you can click the link below.

But there is no such link in below error message.

**Comment by ridwanskaterock** [comment]
halo problem occurred because the database is made the same user, please check the make sure the database before installing the data in the database and empty state

Thanks

**Comment by adadion** [comment]
I've remove all the cicool files, replace with newly extracted cicool, and new empty db. Already fixing permission on applications/config/config.php, database.php, and applications/migrations/001something.php *currently not been able to check on my laptop*.
Basically so the permisssion warning didn't came up. After step 3, after i click finish, it is always redirecting me to the first step wizard. I've got all green status on step 1. My server totally compatible, with php 5.6. All requirement plugins are ready.
And when i tried opening localhost/domain/administrator/ it will redirecting me to 404 page not found. (I've already commenting the first redirect path on file Not_found.php) because if not, it will give me error on that line.

What have i missed here?

**Comment by adadion** [comment]
I've sent my problem to your email mas. Need solution. Thank you.

**Comment by theokyra** [comment]
why no public solution posted here?

**Comment by theokyra** [comment]
I am having issue installing... can't get past the wizzard! Help!
1) wizzard/setup/1
2) Choose language
3) back to wizzard/setup/1

**Comment by ridwanskaterock** [comment]
Can you check database is created ?

and you check for application/config/site.php is exist ?

**Comment by theokyra** [comment]
application/config/site.php does NOT exist in my installation
this file is not par tof what I purchased from themforest... any help?

**Comment by theokyra** [comment]
I changes the mcrypt related line of code from /wizzard.php to true and I was able to pass the wizzard until step 3... then I have thi snew error:
``` 
An Error Was Encountered
The action you have requested is not allowed.
```
![image](https://user-images.githubusercontent.com/40278930/47579133-2bf9c880-d919-11e8-9a9d-f66d4c425847.png)

**Comment by adadion** [comment]
I'm trying to help, if I'm not mistaken, if in the step 3 you're redirected to step 1 again, all you have to do is make sure that the config folder are writable. Because after step 3, cicool will auto creating document named site.php. Would be better if you start to create fresh install of cicool again, just to make sure. *PS: don't forget to make sure the config folder must be writable

**Comment by johnfelipe** [comment]
> I changes the mcrypt related line of code from /wizzard.php to true and I was able to pass the wizzard until step 3... then I have thi snew error:
> 
> ```
> An Error Was Encountered
> The action you have requested is not allowed.
> ```
> ![image](https://user-images.githubusercontent.com/40278930/47579133-2bf9c880-d919-11e8-9a9d-f66d4c425847.png)

i have same issue, how solved i have nginx not apache
