### ISSUE TITLE
API inaccessible

### ISSUE THREAD

**Issue by fleogit** [ridwanskaterock/cicool#363]
Hi CICOOL

I cannot access API from a remote location. 
every thing works perfect from with in your website but from remote postman it fails 
I configured YOUR  demo site as a test and it does not work either.

http://cicool.go-moment.com:443/api/blog/all
 X-Api-Key F1EDC135E49121B53B7F051A1BC8C607
X-Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjoiMyJ9LCJpYXQiOjE1ODM4MDk2NTUsImV4cCI6MTU4Mzg5NjA1NX0.72JxQhsubj3iegPXqfJ2DgtCa9K6WdE5-VQdkrPiYPg

Could not get any response
There was an error connecting to http://cicool.go-moment.com:443/api/blog/all.

please assist

**Comment by ridwanskaterock** [comment]
test with your token and key i am not able to get resource this API because i dont have permission for it 

![image](https://user-images.githubusercontent.com/9270445/76285021-57444400-62d1-11ea-8e77-d62161b50b91.png)

tr with other user admin@admin.com
with token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjoiMSJ9LCJpYXQiOjE1ODM4MjEwMTgsImV4cCI6MTU4MzkwNzQxOH0.ISiS8NRwvye3iWlSN4jf0EHQ7fYQ7zFJcV5th1_j-4c

work well 

![image](https://user-images.githubusercontent.com/9270445/76285121-88bd0f80-62d1-11ea-8689-3b993fb04b8c.png)

if you use other group 
you need assign for permission on this module 
https://cicool.go-moment.com/administrator/access

![image](https://user-images.githubusercontent.com/9270445/76285159-a25e5700-62d1-11ea-97e5-43979afd3960.png)


Thanks

**Comment by fleogit** [comment]
Hi I cannot test I get this error when logging into your live site

An Error Was Encountered
The action you have requested is not allowed.

**Comment by ridwanskaterock** [comment]
Try login again because not allowed is your session has expired
