### ISSUE TITLE
main_layout.php not loading when creating/Adding CRUD, FORM

### ISSUE THREAD

**Issue by krecco** [ridwanskaterock/cicool#49]
I am having problems loading views
crud/add, crud/edit
rest/add, rest/edit

index function of crud / rest works ok. Other controllers are also working properly.

![screen shot 2017-04-10 at 21 03 24](https://cloud.githubusercontent.com/assets/27236010/24878121/238f9286-1e32-11e7-8324-bca537b0734b.png)
![screen shot 2017-04-10 at 21 03 02](https://cloud.githubusercontent.com/assets/27236010/24878118/2381c052-1e32-11e7-8c39-1bcf9919dfe6.png)
![screen shot 2017-04-10 at 21 00 31](https://cloud.githubusercontent.com/assets/27236010/24878120/2385f3d4-1e32-11e7-9e2f-5989f684d366.png)
![screen shot 2017-04-10 at 21 00 39](https://cloud.githubusercontent.com/assets/27236010/24878119/23832230-1e32-11e7-93f7-7393804c46aa.png)

**Comment by Fazmin** [comment]
Add new REST does not work either same issue.

**Comment by ridwanskaterock** [comment]
prior to debug try to open the file index.php

precisely in line 56 you will find a code like the following

define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'production');

you like to change to be like this

define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
to see what pops up error

then you try to run back,
what response in the can?

**Comment by Fazmin** [comment]
@krecco, sorry for commenting on this thread. 
@ridwanskaterock but I still get this on the console and the attached screenshot. #48  
GET http://<site>/administrator/crud/add 500 (Internal Server Error)
jquery.hotkeys.js:204 Uncaught ReferenceError: jQuery is not defined
    at jquery.hotkeys.js:204
(anonymous) @ jquery.hotkeys.js:204
jquery.floatThead.min.js:63 Uncaught ReferenceError: jQuery is not defined
    at jquery.floatThead.min.js:63
(anonymous) @ jquery.floatThead.min.js:63
add:26 Uncaught ReferenceError: jQuery is not defined
    at add:26
![screenshot 2](https://cloud.githubusercontent.com/assets/1432117/24892394/471b39ea-1e4a-11e7-89f4-5391c693e7c9.jpg)

**Comment by ridwanskaterock** [comment]
What OS do you use?

or you can try change value for log_threshold to 4 for seee all message error etc

image

thanks

**Comment by graufb** [comment]
@Fazmin its ok, because we have the same error.
@ridwanskaterock its a db  - select error:

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

INFO - 2017-04-11 07:50:33 --> Config Class Initialized
INFO - 2017-04-11 07:50:33 --> Hooks Class Initialized
DEBUG - 2017-04-11 07:50:33 --> UTF-8 Support Enabled
INFO - 2017-04-11 07:50:33 --> Utf8 Class Initialized
INFO - 2017-04-11 07:50:33 --> URI Class Initialized
INFO - 2017-04-11 07:50:33 --> Router Class Initialized
INFO - 2017-04-11 07:50:33 --> Output Class Initialized
INFO - 2017-04-11 07:50:33 --> Security Class Initialized
DEBUG - 2017-04-11 07:50:33 --> Global POST, GET and COOKIE data sanitized
INFO - 2017-04-11 07:50:33 --> CSRF cookie sent
INFO - 2017-04-11 07:50:33 --> Input Class Initialized
INFO - 2017-04-11 07:50:33 --> Language Class Initialized
INFO - 2017-04-11 07:50:33 --> Loader Class Initialized
INFO - 2017-04-11 07:50:33 --> Helper loaded: url_helper
INFO - 2017-04-11 07:50:33 --> Helper loaded: app_helper
INFO - 2017-04-11 07:50:33 --> Helper loaded: form_helper
INFO - 2017-04-11 07:50:33 --> Helper loaded: security_helper
INFO - 2017-04-11 07:50:33 --> Helper loaded: download_helper
INFO - 2017-04-11 07:50:33 --> Helper loaded: captcha_helper
INFO - 2017-04-11 07:50:33 --> Parser Class Initialized
INFO - 2017-04-11 07:50:33 --> User Agent Class Initialized
DEBUG - 2017-04-11 07:50:33 --> Template Class Initialized
INFO - 2017-04-11 07:50:33 --> Form Validation Class Initialized
INFO - 2017-04-11 07:50:33 --> Controller Class Initialized
INFO - 2017-04-11 07:50:33 --> Database Driver Class Initialized
INFO - 2017-04-11 12:50:33 --> Helper loaded: directory_helper
DEBUG - 2017-04-11 12:50:33 --> Session: "sess_save_path" is empty; using "session.save_path" value from php.ini.
INFO - 2017-04-11 12:50:33 --> Session: Class initialized using 'files' driver.
INFO - 2017-04-11 12:50:33 --> Language file loaded: language/english/aauth_lang.php
DEBUG - 2017-04-11 12:50:33 --> Config file loaded: /var/www/html/crud/v1/application/config/aauth.php
INFO - 2017-04-11 12:50:33 --> Database Driver Class Initialized
DEBUG - 2017-04-11 12:50:33 --> Cc_app class already loaded. Second attempt ignored.
INFO - 2017-04-11 12:50:33 --> Model Class Initialized
ERROR - 2017-04-11 12:50:33 --> Query error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'crud.crud_input_type.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Invalid query: SELECT *
FROM `crud_input_type`
GROUP BY `validation_group`
INFO - 2017-04-11 12:50:33 --> Language file loaded: language/english/db_lang.php

Site runs on vps clean install
OS ubuntu 16.04
PHP 7.0.15-0ubuntu0.16.04.4
MySql 5.7.17-0ubuntu0.16.04.2 - (Ubuntu)

**Comment by graufb** [comment]
@ridwanskaterock 
I have "solved" it by changing msql setting sql_mode to ''
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

It´s a test server so I don't care. 

But you should update your code on next release.

**Comment by Fazmin** [comment]
@graufb Great Job, where did you make the change? is it the aauth.php? Thank you in advance. I assume many people must have had this issue ha?

**Comment by graufb** [comment]
@ridwanskaterock no it's a setting on mysql server. 

Your queries are:
SELECT field1, field2, field3
......
......
GROUP BY field1

and that throws an error in mysql if ONLY_FULL_GROUP_BY is turned on. 

Why you should check your queries:
http://mechanics.flite.com/blog/2013/02/12/why-i-use-only-full-group-by/

**Comment by ridwanskaterock** [comment]
Hii thaks for it,

For current version you can add manualy / run manualy on PHPMYADMIN or sql command.

Because i dont have problem on install on server linux, windows, mac for it

But i will add sql statement on next version

Thanks

**Comment by Fazmin** [comment]
Thanks @graufb and @ridwanskaterock Issue resolved.

**Comment by hunterhn** [comment]
Thanks  @graufb for the tip, it worked fine.

**Comment by jerfran** [comment]
Well, I use serverpilot and to fix this issue just follow this guide: 

https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html

**Comment by sheikhrehman** [comment]
Where is the solution? I think @graufb does not exist.
